// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package esi.rentit9.rest;

import java.util.List;

privileged aspect PlantResourceList_Roo_JavaBean {
    
    public List<PlantResource> PlantResourceList.getPlant() {
        return this.plant;
    }
    
    public void PlantResourceList.setPlant(List<PlantResource> plant) {
        this.plant = plant;
    }
    
}
