// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package esi.rentit9.domain;

import esi.rentit9.domain.BuildIt;

privileged aspect BuildIt_Roo_JavaBean {
    
    public String BuildIt.getName() {
        return this.name;
    }
    
    public void BuildIt.setName(String name) {
        this.name = name;
    }
    
}
