// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package esi.rentit9.domain;

import esi.rentit9.domain.PurchaseOrderLine;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PurchaseOrderLine_Roo_Configurable {
    
    declare @type: PurchaseOrderLine: @Configurable;
    
}
